name: Unit testing with Conda

on:
  push

jobs:

  conda_build_test:
    name: Conda Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.7"]
    steps:
      - uses: actions/checkout@v2
      - uses: goanpeca/setup-miniconda@v1
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: foo
      - name: Conda Upload
        shell: bash -l {0}
        run: |
          conda config --add channels conda-forge
          conda config --add channels underworldcode
          conda install petsc4py mpi4py compilers
          conda install stripy h5py sympy pint
      - name: Test quagmire
        shell: bash -l {0}
        run: |
          conda install pytest
          conda install pip
          pip install -e .
          python -m pytest -v
